### ISSUE TITLE
'require' cannot load 

### ISSUE THREAD

**Issue by phanilav** [VikramShetty/PlayWithTweets#1]
I followed the steps mentioned and when I try to execute the .bat the execution crashes and then I try to execute from .rb I get following error. 
```
c:/ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ./lib/Tags (LoadError)
	from c:/ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from G:/MY Research/Datasets/Twitter/twitter_ruby/PlayWithTweets-master/lib/ReadTags.rb:1:in `<top (required)>'
	from c:/ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from c:/ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from twitterGeo.rb:2:in `<main>'

FAIL: 1
```

**Comment by VikramShetty** [comment]
You are right. There was a file missing and now it's been added. Get latest code and it should work.
